version: 1.0.{build}
configuration: Relase
platform: x64
init:
- cmd: choco upgrade chocolatey
install:
- cmd: choco install tinycc
- cmd : choco install cmake
before_build:
- cmd: cd src
- cmd: cmake
- cmd: tcc -o ejem.exe -run helloworld.c
- cmd: dir


