version: 1.0.{build}
configuration: Relase
image: Visual Studio 2015
platform: x64
init:
- cmd: choco upgrade chocolatey
install:
- cmd: choco install tinycc
before_build:
- echo Running cmake...
- cmd: cd src
- cmd: cmake -G"Visual Studio 14 2015 Win64"
- cmd: tcc -o ejem.exe -run helloworld.c
- cmd: dir
