version: 1.0.{build}
configuration: Relase
platform: x64
init:
- cmd: choco upgrade chocolatey
install:
- cmd: choco install tinycc
before_build:
- cmd: cd scr
build:
- cmd: tcc -o exp helloworld.c
- cmd: -/exp
