version: 1.0.{build}
configuration: Relase
platform: x64
init:
- cmd: choco upgrade chocolatey
install:
- cmd: choco install tinycc
before_build:
- cmd: cd src
- cmd: dir
- cmd: tcc -run helloworld.c
build:
parallel: false
